### ISSUE TITLE
Question regarding GEC

### ISSUE THREAD

**Issue by saramoeini20** [gotutiyan/GEC-Info#5]
Hi,
I'm working in GEC field and have some question. If you will help me i would be thankful.
1) The language I want to work on is low resource and i have to create training and evaluation dataset myself. I saw both parallel format and M2 format. Can you please tell me in which structure i should make my dataset?

2) Are both parallel data and M2 format usable for evaluation metrics?

3) Is there any work that you suggest to me as base work that i start with?

**Comment by gotutiyan** [comment]
Hi, here is my opinion.

===1.===
For training dataset, parallel format is enough. The most simple GEC model may be Seq2Seq model and it can be trained on simple parallel dataset.
For evaluation dataset, please see the answer of the second question.

===2.===
Both formats are useful for evaluation, but which format is better depends on the metric.
- If you use a n-gram based metric, such as GLEU, parallel format is enough.
- If you want to use an edit matching based metric, like M2scorer or ERRANT, M2 format is needed.

===3.===
It's quite difficult to comment about it, but the first approach is to create training and evaluate dataset as parallel format. By using this, you can train a GEC model and evaluate its outputs by a n-gram matching-based metric.
Next, maybe you want to evaluate detail performance, such as Precision, Recall, F0.5 and error type based performance. For this purpose, you need to create an evaluation dataset as M2 format. At the same time, you need to consider what alignment method can be used,  what error type can be consider in your targeted language.

**Comment by saramoeini20** [comment]
Dose creating dataset in M2 format a difficult task? I saw some tools like ERRANT convert from parallel to M2 but I think they are not usable for my language. Can i modify these tools or is it better that i create dataset manually in M2 format?
Also what methods exist for creating artificial data(set)?

**Comment by gotutiyan** [comment]
> Dose creating dataset in M2 format a difficult task?
Probably yes.

When you create dataset in M2 format,
- You need to consider how to segment a sentence. This is easy in a space-separated language (like English) but otherwise (like Japanese) difficult.
- You also need to define error types. For example, ERRANT defines 25 error types for English. Actually, M2 format might work without error type but this is one of the strong benefits of M2 format, so error type is better to be existed.

Maybe you can develop ERRANT-like tools for your targeted language.
- If the segmentation method is determined, alignments between source and target can also be obtained.
- The alignments provide us what edits are exits. Then, you can attach an error type for each edit. Note that you need to additionally develop edit classification method.

M2 format can be created by manually, but edit can be inconsistent. For example, (1) [have eating → has eaten] or (2) [have → has] and [eating → eaten] should be unified with one another. ERRANT-like tools overcome this point.

For creating artiificial data, please refer to [Data Augumentation](https://github.com/gotutiyan/GEC-Info#data-augmentation).
I think back-translation or directly-modification methods are major.

**Comment by saramoeini20** [comment]
Thank you so much for explanation.
