### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by Zari222** [gotutiyan/GEC-Info#6]
Hi,
Regarding dataset format, i was kind of confused. I found out that for training i need parallel format and for testing i need M2 format but
1. Is parallel format just used for training i mean M2 format isn't usable?
2. In parallel format there is no sign or flag that shows this sentence is right or wrong. don't it case problem?

**Comment by gotutiyan** [comment]
Hi,
1.
- Basically, training doesn't need M2 format. 
- Recently both seq2seq and tagging model are major in GEC field, but training a seq2seq model doesn't need M2 format. Parallel is enough. 
- In contrast, training a tagging model requires alignment information so M2 format is usable. However, it is not required if you take alignment in your own way. For example, when training GECToR (one of the tagging models), only parallel data is needed because GECToR takes alignment its own way. Note that M2 format is just one of the expressions of alignment information between source and target.

2.
- No problem. If you want to know whether the source sentence is right or wrong, you can simply compare the source sentence and the target sentence.

**Comment by Zari222** [comment]
thanks
